#!/bin/bash
set -x


#
# Compile libcgnsoo
#
# Here, the configuration part might be trickier because it has been developped using relatively recent
# version of the autotools. We know that the auto-configuration part will work with these versions of
# the autotools:
#       autoconf 2.61
#       automake 1.10
#       libtool 1.5.24

LIBCGNSOOHOME=`pwd`/libcgnsoo_3.0
if [ -e $LIBCGNSOOHOME -a ! -r $LIBCGNSOOHOME/platforms/$WM_OPTIONS/lib/libcgnsoo3.a ]
then
    pushd $LIBCGNSOOHOME

    # Verify the bootstrap script against your own installation of the autotools
    ./bootstrap
    ./configure --prefix=$LIBCGNSOOHOME/platforms/$WM_OPTIONS --with-CGNSLIBHOME=/usr/
    make
    make install

    popd
fi
